name: a1rb4Ck's place
markdown: kramdown
permalink:
  /blog/:year/:month/:day/:title
  /404.html
gems:
  - jekyll-seo-tag
twitter:
  username: aIrb4Ck
image:
  twitter: /img/twt.png
  linkedin: /img/lkdn.png
  height: 100
  width: 100
